const $=x=>document.getElementById(x),R=n=>Math.floor(Math.random()*n),pick=a=>a[R(a.length)],shuffle=a=>{for(let i=a.length-1;i;i--){let j=R(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
const ACTS=['Het Holle Woud','De Ambermoerassen','De Gebroken Hemel'];
const HEROES=[{name:'Vexa',title:'Maansnijder',sprite:0,hp:72,kind:'attack',passive:'Eerste aanval per beurt doet +3 schade.',pool:['maan','jacht','mes','schaduw']},{name:'Myr',title:'Dauwziener',sprite:1,hp:64,kind:'skill',passive:'Iedere derde Skill geneest 2 HP.',pool:['dauw','wortel','geest','bloei']},{name:'Korr',title:'Schubwacht',sprite:2,hp:84,kind:'block',passive:'Behoud maximaal 5 Block tussen beurten.',pool:['schub','ijzer','wacht','storm']},{name:'Pip',title:'Vonkbrouwer',sprite:3,hp:68,kind:'chaos',passive:'Iedere vierde kaart kost 0 Energy.',pool:['vonk','brouw','inkt','chaos']}];
const CARDS={slash:{n:'Sikkelhaal',c:1,t:'attack',d:'Doe 7 schade.',fx:{dmg:7}},guard:{n:'Schorsschild',c:1,t:'skill',d:'Krijg 6 Block.',fx:{block:6}},spark:{n:'Wilde Vonk',c:1,t:'attack',d:'Doe 5 schade. Trek 1.',fx:{dmg:5,draw:1}},bloom:{n:'Nachtbloei',c:1,t:'skill',d:'Krijg 5 Block en genees 2.',fx:{block:5,heal:2}}};
const FORMS=[['beet','attack','Doe {a} schade.',x=>({dmg:5+x})],['slag','attack','Doe {a} schade, tweemaal.',x=>({dmg:3+~~(x/2),hits:2})],['storm','attack','Doe {a} schade. Trek 1.',x=>({dmg:4+x,draw:1})],['schild','skill','Krijg {b} Block.',x=>({block:6+x})],['vlucht','skill','Krijg {b} Block. Trek 1.',x=>({block:3+x,draw:1})],['sap','skill','Krijg {b} Block en genees 2.',x=>({block:4+x,heal:2})],['drift','power','Krijg {s} Kracht.',x=>({str:1+(x>3)})],['doorn','power','Aanvallers krijgen {t} schade.',x=>({thorns:2+(x>2)})],['ritueel','power','Krijg elke beurt 1 Kracht.',x=>({rage:1})],['gif','attack','Doe {a} schade en {p} Gif.',x=>({dmg:3+x,poison:2+x})],['echo','skill','Trek 2 kaarten.',x=>({draw:2})],['breuk','attack','Doe {a} zware schade.',x=>({dmg:12+x*2})]];
FORMS.push(['golf','attack','Doe {a} schade aan ALLE vijanden.',x=>({dmg:4+x,aoe:true})],['offer','skill','Trek 3. Exhaust.',x=>({draw:3,exhaust:true})]);HEROES.forEach((h,hi)=>h.pool.forEach((word,w)=>FORMS.forEach((f,j)=>{let x=(w+j)%5,id=`h${hi}_${w}_${j}`,fx=f[3](x),cost=j===10?1:j===11?2:j===12?1:j===13?0:(j%4===0?0:1),v={a:(fx.dmg||0)*(fx.hits||1),b:fx.block||0,s:fx.str||0,t:fx.thorns||0,p:fx.poison||0};CARDS[id]={n:`${word[0].toUpperCase()+word.slice(1)}${f[0]}`,c:cost,t:f[1],d:f[2].replace(/\{(.)\}/g,(_,k)=>v[k]),fx,hero:hi}})));
const NAMES=['Doornkever','Lantaarnmot','Moswolf','Beenderkrab','Moeraspad','Kristalslang','Rookduivel','Schaduwspin','Wortelreus','Asuil','Zwamschild','Amberdemon','Bloedbok','Harsbeer','Klokraaf','Donderhert','Gifslak','Sporeling','Kettingwesp','Hollegeest','Maankever','Vlamvos','Steendoorn','Nachtkiem'],ENEMIES=[];for(let act=0;act<3;act++)for(let i=0;i<24;i++){let elite=i>=20,h=24+act*22+i*3+(elite?38:0),role=['striker','guard','poison','support','healer','exploder','summoner','debuffer'][i%8],a=role==='guard'?[[5+act*2,'block'],[6+act*3,'attack']]:role==='poison'?[[2+act,'poison'],[7+act*3,'attack']]:role==='support'?[[2+act,'strAll'],[5+act*2,'attack']]:role==='healer'?[[6+act*3,'healAll'],[6+act*2,'attack']]:role==='exploder'?[[3,'charge'],[16+act*7,'attack']]:role==='summoner'?[[1,'summon'],[7+act*2,'attack']]:role==='debuffer'?[[2,'weak'],[8+act*3,'attack']]:[[7+act*4+i%5,'attack'],[2+act,'str']];ENEMIES.push({n:`${NAMES[i]} ${['Jong','Verhard','Oeroud'][act]}`,s:i%12,h,a,role,elite})}
const BOSSES=[{n:'De Hollekoning',s:11,h:145,a:[[14,'attack'],[3,'str'],[22,'attack'],[15,'block'],[30,'attack']]},{n:'Moeder Moeras',s:8,h:225,a:[[18,'attack'],[6,'poison'],[28,'attack'],[4,'str']]},{n:'De Gebroken Zon',s:9,h:320,a:[[24,'attack'],[25,'block'],[5,'str'],[42,'attack']]}];
const RELICS=[['Amberhart','+8 maximale HP.','maxhp'],['Vossenstaart','Start met 1 Kracht.','str'],['Mosring','Genees 4 na gevecht.','heal'],['Gouden Snavel','25% meer amber.','gold'],['Gebarsten Schild','Start met 7 Block.','block'],['Dauwoog','Trek beurt één extra.','draw'],['Vonkklier','Start met extra Energy.','energy'],['Gifwortel','Eerste aanval: 3 Gif.','poison'],['Spiegelveer','Eerste kaart +4 schade.','mirror'],['Hol Zaad','Powers kosten 1 minder.','power'],['Stalen Schub','Blockkaarten +2.','armor'],['Jagersmaan','Aanvallen +1 schade.','damage']];
const EVENTS=[['De Slapende Reus','Een ademhaling doet de aarde beven.'],['Het Fluistermeer','Je spiegelbeeld vraagt om een herinnering.'],['De Amberboom','Gouden hars stroomt als bloed.'],['Verlaten Nest','Iets glinstert tussen oude veren.'],['De Blinde Handelaar','Hij kent je naam, maar niet je gezicht.'],['De Dansende Sporen','De lucht smaakt naar vergeten dromen.']];let G=null,SELECTED=null,DECK_RETURN='map',DRAG=null,DRAG_SUPPRESS_UNTIL=0,SOUND_ON=localStorage.wildforgeSound!=='off';
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id!=='combat'&&$('combatSettings'))$('combatSettings').classList.add('hidden')}
function init(){$('heroes').innerHTML=HEROES.map((h,i)=>`<div class="hero" onclick="start(${i})"><div class="sprite s${h.sprite}"></div><h3>${h.name}</h3><b>${h.title}</b><p>${h.passive}</p></div>`).join('');$('ascension').innerHTML=Array.from({length:21},(_,i)=>`<option value="${i}">Wildheid ${i}</option>`).join('');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
function makeMap(){let types=['⚔','⚔','?','⚔','💰','👹','🔥','⚔','?','⚔','🔥'];return Array.from({length:12},(_,row)=>{let count=row===11?1:3;return Array.from({length:count},(_,lane)=>({id:`${row}-${lane}`,row,lane,type:row===11?'👑':types[(row+lane*2+R(3))%types.length],next:row===11?[]:[lane,Math.min(2,lane+1),Math.max(0,lane-1)].filter((x,i,a)=>a.indexOf(x)===i)}))}).flat()}
function start(hero){let h=HEROES[hero];G={hero,hp:h.hp,max:h.hp,gold:99,potions:2,act:0,step:0,row:0,current:null,map:makeMap(),history:[],asc:+$('ascension').value,deck:['slash','slash','slash','slash','guard','guard','guard','guard','spark','bloom'],relics:[],won:0,removed:0};ensureAudio();sound('start');save();renderMap()}
function save(){localStorage.wildforge=JSON.stringify(G)}function continueRun(){if(localStorage.wildforge){G=JSON.parse(localStorage.wildforge);renderMap()}else show('select')}
function normalizeRun(){if(!G.map){G.row=0;G.current=null;G.history=[];G.map=makeMap()}}
function renderMap(){normalizeRun();show('map');$('mapHero').textContent=`${HEROES[G.hero].name} · W${G.asc}`;$('mapHp').textContent=`${G.hp}/${G.max}`;$('gold').textContent=G.gold;$('deckCount').textContent=`▣ ${G.deck.length} kaarten`;$('actTitle').textContent=`Act ${G.act+1} — ${ACTS[G.act]}`;$('relicStrip').textContent=G.relics.length?`✦ ${G.relics.map(i=>RELICS[i][0]).join(' · ')}`:'Nog geen relieken';let W=1100,H=Math.max(280,$('mapViewport').clientHeight||300),xs=r=>55+r*(W-110)/11,ys=l=>H*(.2+l*.3),openIds=G.row===0?G.map.filter(n=>n.row===0).map(n=>n.id):((G.map.find(n=>n.id===G.current)||{}).next||[]).map(l=>`${G.row}-${l}`);$('mapNodes').innerHTML=G.map.map(n=>{let done=G.history.includes(n.id),open=openIds.includes(n.id),state=done?'done':open?'open':'lock',label={'⚔':'Gevecht','?':'Mysterie','💰':'Winkel','👹':'Elite','🔥':'Rust','👑':'Baas'}[n.type];return `<button class="map-node ${state} ${n.type==='👑'?'boss':''}" style="left:${xs(n.row)}px;top:${ys(n.lane)}px" ${open?`onclick="chooseNode('${n.id}')"`:''}>${n.type}<small>${label}</small></button>`}).join('');let lines=[];G.map.filter(n=>n.row<11).forEach(n=>n.next.forEach(l=>{let to=G.map.find(x=>x.row===n.row+1&&(x.lane===l||x.row===11));if(to)lines.push(`<line class="${G.history.includes(n.id)?'reached':''}" x1="${xs(n.row)}" y1="${ys(n.lane)}" x2="${xs(to.row)}" y2="${ys(to.lane)}"/>`)}));$('mapLines').setAttribute('viewBox',`0 0 ${W} ${H}`);$('mapLines').innerHTML=lines.join('');setTimeout(()=>{$('mapViewport').scrollLeft=Math.max(0,xs(G.row)-innerWidth*.35)},0)}
function chooseNode(id){let n=G.map.find(x=>x.id===id);G.pendingNode=id;node(n.type)}
function node(t){if(t==='🔥')return rest();if(t==='?')return event();if(t==='💰')return shop();beginFight(t==='👹',t==='👑')}
function enemyCopy(e,scale=1){let x=JSON.parse(JSON.stringify(e));x.h=Math.round(x.h*scale);x.a=x.a.map(a=>[a[1]==='attack'?Math.round(a[0]*scale):a[0],a[1]]);return x}
function encounter(elite,boss){let scale=1+G.asc*.025;if(boss){let group=[enemyCopy(BOSSES[G.act],scale)];if(G.act>0)group.push(enemyCopy(ENEMIES[G.act*24+R(8)],scale*.72));return group}let count=elite?1+R(2):1+R(Math.min(4,2+G.act)),pool=ENEMIES.slice(G.act*24,G.act*24+(elite?24:20));return Array.from({length:count},()=>enemyCopy(pick(pool),scale*(count>2?.72:count>1?.84:1)))}
function has(type){return G.relics.some(i=>RELICS[i][2]===type)}function beginFight(elite=false,boss=false){let group=encounter(elite,boss),enemies=group.map(e=>({...e,hp:e.h,max:e.h,block:0,str:0,poison:0,charge:0}));G.fight={enemies,turn:0,block:has('block')?7:0,str:has('str')?1:0,weak:0,thorns:0,rage:0,poison:0,played:0,skillCount:0,draw:shuffle([...G.deck]),discard:[],exhaust:[],hand:[],elite,boss};G.potions=G.potions??2;SELECTED=null;show('combat');$('combatName').textContent=HEROES[G.hero].name;$('playerName').textContent=HEROES[G.hero].name;$('maxHp').textContent=G.max;$('playerSprite').className=`sprite s${HEROES[G.hero].sprite}`;sound('start');newTurn()}
function draw(n){let f=G.fight;while(n--){if(!f.draw.length)f.draw=shuffle(f.discard.splice(0));if(f.draw.length&&f.hand.length<10)f.hand.push(f.draw.pop())}}
function newTurn(){let f=G.fight;f.turn++;f.energy=3+(has('energy')&&f.turn===1);f.block=HEROES[G.hero].kind==='block'?Math.min(5,f.block):0;f.str+=f.rage;f.played=0;draw(5-f.hand.length+(has('draw')&&f.turn===1));renderCombat()}
function realCard(id){return CARDS[id.replace('+','')]}function cardHTML(id,i,playable=false,price=''){let c=realCard(id),up=id.endsWith('+'),cost=Math.max(0,c.c-(has('power')&&c.t==='power')),free=playable&&HEROES[G.hero].kind==='chaos'&&(G.fight.played+1)%4===0,dis=playable&&!free&&cost>G.fight.energy,drag=playable?`data-index="${i}" data-type="${c.t}" data-aoe="${!!c.fx.aoe}" role="button" aria-label="${c.n}: ${c.d}"`:'';return `<div class="card ${c.t} ${up?'upgraded':''} ${dis?'disabled':''} ${playable&&SELECTED===i?'selected':''}" ${drag} ${playable?`onclick="play(${i})"`:''}><span class="cost">${free?0:cost}</span><h4>${c.n}${up?' +':''}</h4><p>${c.d}</p>${price?`<span class="price">${price} ◈</span>`:''}<em>${c.t==='attack'?'AANVAL':c.t==='skill'?'VAARDIGHEID':'KRACHT'}</em></div>`}
function intentText(e,f){let a=e.a[(f.turn-1)%e.a.length],k=a[1];return k==='attack'?`⚔ ${a[0]+e.str}`:k==='block'?`🛡 ${a[0]}`:k==='poison'?`☠ ${a[0]}`:k==='healAll'?`♥ ${a[0]}`:k==='summon'?'✚ ROEP':k==='weak'?`▽ ${a[0]}`:k==='charge'?'⚡ LAADT':`↑ ${a[0]}`}
function renderCombat(){let f=G.fight;f.exhaust??=[];let selected=SELECTED===null?null:realCard(f.hand[SELECTED]),aoe=!!(selected&&selected.t==='attack'&&selected.fx.aoe),targeting=!!(selected&&selected.t==='attack');$('hp').textContent=G.hp;$('energy').textContent=f.energy;$('turnLabel').textContent=`Beurt ${f.turn}`;$('playerHpText').textContent=`${G.hp} / ${G.max}`;$('playerBar').style.width=`${Math.max(0,G.hp/G.max*100)}%`;$('playerFx').textContent=`🛡 ${f.block}  ↑ ${f.str}  ▽ ${f.weak}  ☠ ${f.poison}`;$('drawCount').textContent=f.draw.length;$('discardCount').textContent=f.discard.length;$('exhaustCount').textContent=f.exhaust.length;$('potionCount').textContent=G.potions;$('combatRelics').textContent=G.relics.map(i=>`✦ ${RELICS[i][0]}`).join('  ');$('soundToggle').textContent=SOUND_ON?'GELUID AAN':'GELUID UIT';$('combatTip').textContent=SELECTED===null?'Sleep een kaart omhoog':aoe?'Richt op de hele vijandenrij':'Kies één vijand';$('enemies').style.setProperty('--enemy-count',Math.max(1,Math.min(4,f.enemies.length)));$('enemyZone').classList.toggle('aoe-preview',aoe);$('enemies').innerHTML=f.enemies.map((e,i)=>`<div id="enemy${i}" data-enemy-index="${i}" class="enemy-unit ${e.hp<=0?'dead':''} ${targeting&&e.hp>0?'targetable':''}" onclick="targetEnemy(${i})"><div class="intent">${e.hp>0?intentText(e,f):'☠'}</div><div class="enemy-sprite e${e.s%12}"></div><div class="nameplate"><b>${e.n}</b><div class="health"><i style="width:${Math.max(0,e.hp/e.max*100)}%"></i><span>${Math.max(0,e.hp)} / ${e.max}</span></div><div class="status">🛡 ${e.block} ↑ ${e.str} ☠ ${e.poison}</div></div></div>`).join('');$('hand').innerHTML=f.hand.map((id,i)=>cardHTML(id,i,true)).join('');bindCardGestures()}
function play(i){if(Date.now()<DRAG_SUPPRESS_UNTIL)return;let f=G.fight,c=realCard(f.hand[i]),cost=Math.max(0,c.c-(has('power')&&c.t==='power')),free=HEROES[G.hero].kind==='chaos'&&(f.played+1)%4===0;if(!free&&cost>f.energy)return;if(c.t==='attack'){SELECTED=SELECTED===i?null:i;return renderCombat()}resolveCard(i)}
function targetEnemy(target=0){if(SELECTED===null)return;let c=realCard(G.fight.hand[SELECTED]);resolveCard(SELECTED,c.fx.aoe?0:target)}
function resolveCard(i,target=0){let f=G.fight;f.exhaust??=[];let id=f.hand[i],c=realCard(id),up=id.endsWith('+'),mul=up?1.3:1,cost=Math.max(0,c.c-(has('power')&&c.t==='power')),free=HEROES[G.hero].kind==='chaos'&&(f.played+1)%4===0;if(!free&&cost>f.energy)return;f.energy-=free?0:cost;f.played++;let x=c.fx,e=f.enemies[target]||f.enemies.find(e=>e.hp>0);if(x.dmg&&e){let bonus=f.str+(HEROES[G.hero].kind==='attack'&&f.played===1?3:0)+(has('damage')?1:0)+(has('mirror')&&f.played===1?4:0),amount=Math.round((x.dmg*mul+bonus)*(x.hits||1)*(f.weak?0.75:1));if(x.aoe)f.enemies.forEach((z,j)=>{if(z.hp>0)damageEnemy(z,amount,j)});else damageEnemy(e,amount,target);if(has('poison')&&f.played===1)e.poison+=3}if(x.block){f.block+=Math.round(x.block*mul)+(has('armor')?2:0);sound('block')}if(x.heal)G.hp=Math.min(G.max,G.hp+Math.ceil(x.heal*mul));if(x.draw)draw(x.draw);if(x.str)f.str+=Math.ceil(x.str*mul);if(x.thorns)f.thorns+=Math.ceil(x.thorns*mul);if(x.rage)f.rage+=x.rage;if(x.poison&&e)e.poison+=Math.ceil(x.poison*mul);if(c.t==='skill'&&HEROES[G.hero].kind==='skill'&&++f.skillCount%3===0)G.hp=Math.min(G.max,G.hp+2);let used=f.hand.splice(i,1)[0];if(x.exhaust)f.exhaust.push(used);else f.discard.push(used);SELECTED=null;if(f.enemies.every(e=>e.hp<=0))return win();renderCombat()}
function bindCardGestures(){document.querySelectorAll('#hand .card[data-index]:not(.disabled)').forEach(card=>card.addEventListener('pointerdown',startCardDrag))}
function startCardDrag(ev){if(DRAG||ev.button>0)return;let el=ev.currentTarget,index=+el.dataset.index,c=realCard(G.fight.hand[index]),rect=el.getBoundingClientRect();DRAG={el,index,pointerId:ev.pointerId,startX:ev.clientX,startY:ev.clientY,lastX:ev.clientX,lastY:ev.clientY,rect,moved:false,attack:c.t==='attack',aoe:!!c.fx.aoe};try{el.setPointerCapture(ev.pointerId)}catch(e){}window.addEventListener('pointermove',moveCardDrag,{passive:false});window.addEventListener('pointerup',endCardDrag);window.addEventListener('pointercancel',cancelCardDrag)}
function moveCardDrag(ev){let d=DRAG;if(!d||ev.pointerId!==d.pointerId)return;let dx=ev.clientX-d.startX,dy=ev.clientY-d.startY;if(!d.moved&&Math.hypot(dx,dy)>7){d.moved=true;SELECTED=null;d.el.classList.add('dragging')}if(!d.moved)return;ev.preventDefault();d.lastX=ev.clientX;d.lastY=ev.clientY;d.el.style.transform=`translate3d(${dx}px,${dy}px,0) scale(1.045) rotate(${Math.max(-4,Math.min(4,dx/35))}deg)`;let upward=dy<-18,hover=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.enemy-unit');document.querySelectorAll('#enemies .enemy-unit').forEach(x=>{x.classList.toggle('targetable',d.attack&&upward&&!x.classList.contains('dead'));x.classList.remove('drag-over')});if(d.attack&&!d.aoe&&upward&&hover&&!hover.classList.contains('dead'))hover.classList.add('drag-over');$('enemyZone').classList.toggle('aoe-preview',d.attack&&d.aoe&&upward);$('combatTip').textContent=!upward?'Sleep verder omhoog':d.aoe?'Laat los: raak alle vijanden':d.attack?'Laat los boven je doelwit':'Laat los om te spelen';drawTargetPath(d,ev.clientX,ev.clientY,upward&&d.attack)}
function drawTargetPath(d,x,y,active){let layer=$('targetingLayer'),path=$('targetingPath');layer.classList.toggle('active',active);if(!active)return;let combat=$('combat').getBoundingClientRect(),sx=d.rect.left+d.rect.width/2-combat.left,sy=d.rect.top-combat.top,ex=x-combat.left,ey=y-combat.top,cy=Math.min(sy,ey)-Math.max(25,Math.abs(sy-ey)*.24);path.setAttribute('d',`M ${sx} ${sy} Q ${(sx+ex)/2} ${cy} ${ex} ${ey}`)}
function dragTargetAt(x,y){let node=document.elementFromPoint(x,y)?.closest('.enemy-unit');if(!node||node.classList.contains('dead'))return-1;return +node.dataset.enemyIndex}
function clearDragVisuals(){let d=DRAG;if(d){d.el.classList.remove('dragging');d.el.style.transform=''}$('targetingLayer').classList.remove('active');$('enemyZone').classList.remove('aoe-preview');document.querySelectorAll('#enemies .enemy-unit').forEach(x=>x.classList.remove('targetable','drag-over'));window.removeEventListener('pointermove',moveCardDrag);window.removeEventListener('pointerup',endCardDrag);window.removeEventListener('pointercancel',cancelCardDrag)}
function endCardDrag(ev){let d=DRAG;if(!d||ev.pointerId!==d.pointerId)return;let target=dragTargetAt(ev.clientX,ev.clientY),upward=d.startY-ev.clientY>38,shouldPlay=d.moved&&upward&&(!d.attack||d.aoe||target>=0);if(d.moved)DRAG_SUPPRESS_UNTIL=Date.now()+450;clearDragVisuals();DRAG=null;if(shouldPlay){try{navigator.vibrate&&navigator.vibrate(12)}catch(e){}resolveCard(d.index,d.aoe?0:Math.max(0,target))}else if(d.moved){SELECTED=null;renderCombat()}}
function cancelCardDrag(ev){let d=DRAG;if(!d||ev.pointerId!==d.pointerId)return;let moved=d.moved;clearDragVisuals();DRAG=null;if(moved){DRAG_SUPPRESS_UNTIL=Date.now()+450;SELECTED=null;renderCombat()}}
function damageEnemy(e,n,i){let t=Math.max(0,n-e.block);e.block=Math.max(0,e.block-n);e.hp-=t;sound('hit');setTimeout(()=>animate(`enemy${i}`,'hit'),0)}function animate(id,c){let e=$(id);if(!e)return;e.classList.remove(c);void e.offsetWidth;e.classList.add(c)}
function endTurn(){SELECTED=null;let f=G.fight;f.discard.push(...f.hand.splice(0));f.enemies.forEach(e=>{if(e.hp>0&&e.poison){e.hp-=e.poison;e.poison=Math.max(0,e.poison-1)}});if(f.enemies.every(e=>e.hp<=0))return win();for(let e of f.enemies.filter(e=>e.hp>0)){let a=e.a[(f.turn-1)%e.a.length],v=a[0],k=a[1];if(k==='attack'){let raw=v+e.str,hit=Math.max(0,raw-f.block);f.block=Math.max(0,f.block-raw);G.hp-=hit;if(hit&&f.thorns)e.hp-=f.thorns;sound('hurt');animate('playerSprite','hit')}else if(k==='block')e.block+=v;else if(k==='str')e.str+=v;else if(k==='poison')f.poison+=v;else if(k==='weak')f.weak+=v;else if(k==='strAll')f.enemies.filter(x=>x.hp>0).forEach(x=>x.str+=v);else if(k==='healAll')f.enemies.filter(x=>x.hp>0).forEach(x=>x.hp=Math.min(x.max,x.hp+v));else if(k==='charge')e.block+=5;else if(k==='summon'&&f.enemies.length<4){let s=enemyCopy(ENEMIES[G.act*24+R(8)],.55);f.enemies.push({...s,hp:s.h,max:s.h,block:0,str:0,poison:0})}}if(f.poison){G.hp-=f.poison;f.poison=Math.max(0,f.poison-1)}if(f.weak)f.weak--;if(G.hp<=0)return lose();if(f.enemies.every(e=>e.hp<=0))return win();newTurn()}
function rewardPool(){return shuffle(Object.keys(CARDS).filter(id=>(CARDS[id].hero===undefined&&!['slash','guard'].includes(id))||CARDS[id].hero===G.hero)).slice(0,3)}
function win(){let f=G.fight;G.won++;G.gold+=Math.round((f.elite?38:18)*(has('gold')?1.25:1));if(has('heal'))G.hp=Math.min(G.max,G.hp+4);if(f.boss||f.elite){let o=RELICS.map((_,i)=>i).filter(i=>!G.relics.includes(i));if(o.length)G.relics.push(pick(o));applyRelics()}$('rewards').innerHTML=rewardPool().map(id=>`<div onclick="take('${id}')">${cardHTML(id,0)}</div>`).join('');show('reward')}
function applyRelics(){if(has('maxhp')&&!G.amberApplied){G.max+=8;G.hp+=8;G.amberApplied=true}}function take(id){G.deck.push(id);advance()}function skipReward(){advance()}function advance(){normalizeRun();let chosen=G.pendingNode||G.current;if(chosen&&!G.history.includes(chosen))G.history.push(chosen);G.current=chosen;G.pendingNode=null;G.row++;G.step=G.row;if(G.row>=12){G.act++;if(G.act>=3)return victory();G.row=0;G.step=0;G.current=null;G.history=[];G.map=makeMap()}save();renderMap()}
function rest(){$('choiceTitle').textContent='Rustplaats';$('choiceText').textContent='De vlam luistert.';$('choices').innerHTML=`<button onclick="healRest()">RUST — genees ${Math.ceil(G.max*.3)} HP</button><button onclick="upgradeChoice()">SMEDEN — verbeter een kaart</button>`;show('choice')}function healRest(){G.hp=Math.min(G.max,G.hp+Math.ceil(G.max*.3));advance()}function upgradeChoice(){let c=G.deck.filter(x=>!x.endsWith('+'));if(c.length){let id=pick(c),i=G.deck.indexOf(id);G.deck[i]=id+'+'}advance()}
function event(){let ev=pick(EVENTS);$('choiceTitle').textContent=ev[0];$('choiceText').textContent=ev[1];$('choices').innerHTML=`<button onclick="eventTake('power')">RAAK AAN — verlies 8 HP, krijg een reliek</button><button onclick="eventTake('gold')">DOORZOEK — krijg 55 amber</button><button class="ghost" onclick="advance()">WEGGAAN</button>`;show('choice')}function eventTake(x){if(x==='power'){G.hp=Math.max(1,G.hp-8);let o=RELICS.map((_,i)=>i).filter(i=>!G.relics.includes(i));if(o.length)G.relics.push(pick(o));applyRelics()}else G.gold+=55;advance()}
function shop(){show('shop');$('shopGold').textContent=G.gold;$('removeCost').textContent=75+G.removed*25;$('wares').innerHTML=rewardPool().map((id,i)=>`<div onclick="buyCard('${id}',${55+i*12})">${cardHTML(id,0,false,55+i*12)}</div>`).join('')}function buyCard(id,cost){if(G.gold<cost)return;G.gold-=cost;G.deck.push(id);shop()}function removeCardShop(){let cost=75+G.removed*25;if(G.gold<cost||G.deck.length<=5)return;let i=G.deck.findIndex(x=>x.startsWith('slash')||x.startsWith('guard'));if(i<0)i=R(G.deck.length);G.deck.splice(i,1);G.gold-=cost;G.removed++;shop()}function leaveNode(){advance()}
let AUDIO=null;function ensureAudio(){if(AUDIO)return AUDIO;try{AUDIO=new(window.AudioContext||window.webkitAudioContext)()}catch(e){}return AUDIO}function sound(type){if(!SOUND_ON)return;let a=ensureAudio();if(!a)return;let o=a.createOscillator(),g=a.createGain(),p={hit:[125,.08,'sawtooth'],hurt:[70,.16,'square'],block:[420,.08,'triangle'],start:[220,.25,'sine'],win:[660,.35,'triangle'],potion:[520,.3,'sine']}[type]||[180,.08,'sine'];o.type=p[2];o.frequency.setValueAtTime(p[0],a.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,p[0]*1.7),a.currentTime+p[1]);g.gain.setValueAtTime(.055,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+p[1]);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+p[1])}function toggleCombatSettings(){$('combatSettings').classList.toggle('hidden')}function toggleSound(){SOUND_ON=!SOUND_ON;localStorage.wildforgeSound=SOUND_ON?'on':'off';$('soundToggle').textContent=SOUND_ON?'GELUID AAN':'GELUID UIT';if(SOUND_ON)sound('start')}function usePotion(){if(!G.potions||!G.fight)return;G.potions--;G.hp=Math.min(G.max,G.hp+14);sound('potion');animate('playerSprite','heal');renderCombat()}
function showDeck(combat=false){DECK_RETURN=combat?'combat':'map';$('deckInfo').textContent=`${G.deck.length} kaarten · ${G.relics.length} relieken`;$('deckCards').innerHTML=G.deck.map(id=>cardHTML(id,0)).join('');show('deck')}function closeDeck(){show(DECK_RETURN)}
function showCompendium(){let m=JSON.parse(localStorage.wildforgeMeta||'{}');$('compStats').textContent=`${Object.keys(CARDS).length} kaarten · ${ENEMIES.length+3} vijanden · ${RELICS.length} relieken · beste Wildheid ${m.best||0}`;$('compCards').innerHTML=Object.keys(CARDS).slice(0,30).map(id=>cardHTML(id,0)).join('');show('compendium')}
function victory(){let m=JSON.parse(localStorage.wildforgeMeta||'{}');m.best=Math.max(m.best||0,G.asc);localStorage.wildforgeMeta=JSON.stringify(m);$('overTitle').textContent='De Gebroken Zon buigt';$('summary').textContent=`Voltooid met ${HEROES[G.hero].name} op Wildheid ${G.asc}. ${G.won} gevechten, ${G.deck.length} kaarten en ${G.relics.length} relieken.`;localStorage.removeItem('wildforge');show('gameover')}function lose(){$('overTitle').textContent='De vlam dooft…';$('summary').textContent=`Act ${G.act+1}, kamer ${G.step+1}. Je deck telde ${G.deck.length} kaarten.`;localStorage.removeItem('wildforge');show('gameover')}init();
